"""Built-in theme instances and the accent-theme factory."""
from __future__ import annotations

from .dataclasses import (
    _DEFAULT_METRICS,
    AppTheme,
    ButtonRole,
    ButtonTheme,
    PaletteTheme,
    SceneTheme,
    TableTheme,
    TrayTheme,
)

DEFAULT_THEME = AppTheme(
    name="vibrant",
    window_background="#f5f7fb",
    panel_background="#ffffff",
    panel_border="#d7deea",
    control_background="#ffffff",
    control_border="#c8d2e3",
    control_focus="#4f7cff",
    text="#162033",
    muted_text="#5d6b82",
    selection_background="#dbeafe",
    selection_text="#0f2344",
    buttons=ButtonTheme(
        default=ButtonRole("#edf2ff", "#dfe8ff", "#cbd9ff", "#1e3154", "#b9c8ee"),
        primary=ButtonRole("#2f66f6", "#2459dc", "#1e49b7", "#ffffff", "#1f4eca"),
        success=ButtonRole("#16a34a", "#12833e", "#0f6b33", "#ffffff", "#0f7a39"),
        danger=ButtonRole("#dc3b4a", "#be2f3d", "#982633", "#ffffff", "#b82f3d"),
        info=ButtonRole("#0891b2", "#067891", "#075f73", "#ffffff", "#077f9b"),
        accent=ButtonRole("#7c3aed", "#6d28d9", "#5b21b6", "#ffffff", "#6d28d9"),
        disabled_background="#e4e9f2",
        disabled_text="#8a96aa",
        disabled_border="#d0d8e5",
    ),
    scene=SceneTheme(
        shelf_fill="#f0f7ff",
        shelf_border="#93b4dd",
        shelf_title="#31537c",
        audio_fill="#24324f",
        audio_border="#36c2ff",
        audio_text="#f8fbff",
        object_fill="#eef3fb",
        object_border="#9aa9bd",
        object_text="#24324f",
        monitor_primary_fill="#d9e8ff",
        monitor_primary_border="#2f66f6",
        monitor_fill="#f5f9ff",
        monitor_border="#64748b",
        monitor_text="#162033",
        monitor_number_primary="#2f66f6",
        monitor_number="#64748b",
        monitor_number_alpha=46,
    ),
    palette=PaletteTheme(
        accent="#0067c0",
        accent_hover="#005a9e",
        accent_pressed="#004578",
        accent_text="#ffffff",
        success="#107c10",
        success_hover="#0e6f0e",
        success_pressed="#0b5a0b",
        success_text="#ffffff",
        warning="#b45309",
        warning_hover="#92400e",
        warning_pressed="#78350f",
        warning_text="#ffffff",
        danger="#c42b1c",
        danger_hover="#b3261e",
        danger_pressed="#8f1f17",
        danger_text="#ffffff",
        info="#0891b2",
        info_hover="#067891",
        info_pressed="#075f73",
        info_text="#ffffff",
    ),
    tables=TableTheme(
        header_background="#eef3fb",
        header_text="#24324f",
        grid_line="#d7deea",
        alternate_row="#f8fbff",
        hover_row="#edf5ff",
        match_background="#dcfce7",
        match_text="#12301c",
    ),
    tray=TrayTheme(
        surface="rgba(249, 249, 249, 245)",
        control="#ffffff",
        row_surface="#ffffff",
        row_surface_hover="#f8fafc",
        primary_display_surface="#0b2f55",
        primary_display_surface_hover="#103f72",
        primary_display_border="#2b6fa3",
        primary_display_text="#f8fbff",
        control_hover="#f3f3f3",
        control_pressed="#e9e9e9",
        border="#d1d1d1",
        subtle_border="#e5e5e5",
        text="#1a1a1a",
        muted="#616161",
        accent="#0067c0",
        accent_hover="#005a9e",
        accent_pressed="#004578",
        accent_text="#ffffff",
        success="#107c10",
        success_hover="#0e6f0e",
        success_pressed="#0b5a0b",
        success_text="#ffffff",
        warning="#b45309",
        warning_hover="#92400e",
        warning_pressed="#78350f",
        warning_text="#ffffff",
        close_hover="#c42b1c",
        close_pressed="#a4261d",
        close_text="#ffffff",
        indicator_connected="#107c10",
        indicator_disconnected="#c42b1c",
        indicator_disabled="#7f8c8d",
        ping_idle="#000000",
        ping_idle_text="#ffffff",
        faceplate_enabled_bg="#0067c0",
        faceplate_enabled_border="#0067c0",
        faceplate_enabled_text="#ffffff",
        faceplate_disabled_bg="#004578",
        faceplate_disabled_border="#004578",
        faceplate_disabled_text="#ffffff",
        faceplate_primary_bg="#cfe2f3",
        faceplate_primary_border="#0067c0",
        faceplate_primary_text="#0a1a33",
        faceplate_unavailable_bg="#e9e9e9",
        faceplate_unavailable_border="transparent",
        faceplate_unavailable_text="#616161",
    ),
    metrics=_DEFAULT_METRICS,
)

DARK_THEME = AppTheme(
    name="dark",
    window_background="#10151d",
    panel_background="#171f2b",
    panel_border="#324155",
    control_background="#111923",
    control_border="#40536b",
    control_focus="#4db6e8",
    text="#eef4fb",
    muted_text="#a8b5c6",
    selection_background="#1d4f6f",
    selection_text="#ffffff",
    buttons=ButtonTheme(
        default=ButtonRole("#223047", "#2b3b55", "#182235", "#eef4fb", "#40536b"),
        primary=ButtonRole("#2c7be5", "#2368c7", "#1c55a6", "#ffffff", "#3f8ff2"),
        success=ButtonRole("#168957", "#13764b", "#105f3e", "#ffffff", "#20a66b"),
        danger=ButtonRole("#c24155", "#a93448", "#872a3b", "#ffffff", "#d95b6d"),
        info=ButtonRole("#0f91a5", "#0b7889", "#0a6170", "#ffffff", "#18a8bd"),
        accent=ButtonRole("#8b5cf6", "#7c3aed", "#6d28d9", "#ffffff", "#a78bfa"),
        disabled_background="#1b2431",
        disabled_text="#66758a",
        disabled_border="#2d3a4d",
    ),
    scene=SceneTheme(
        shelf_fill="#142436",
        shelf_border="#3f6b8f",
        shelf_title="#b7d7f0",
        audio_fill="#0b1722",
        audio_border="#4db6e8",
        audio_text="#f3f9ff",
        object_fill="#1c2836",
        object_border="#617388",
        object_text="#e6edf5",
        monitor_primary_fill="#183657",
        monitor_primary_border="#4db6e8",
        monitor_fill="#202b38",
        monitor_border="#7b8ca1",
        monitor_text="#eef4fb",
        monitor_number_primary="#7dd3fc",
        monitor_number="#9fb0c3",
        monitor_number_alpha=70,
    ),
    palette=PaletteTheme(
        accent="#60cdff",
        accent_hover="#8bddff",
        accent_pressed="#0098d4",
        accent_text="#003547",
        success="#16a34a",
        success_hover="#22c55e",
        success_pressed="#15803d",
        success_text="#ffffff",
        warning="#f59e0b",
        warning_hover="#fbbf24",
        warning_pressed="#d97706",
        warning_text="#241400",
        danger="#c24155",
        danger_hover="#d95b6d",
        danger_pressed="#872a3b",
        danger_text="#ffffff",
        info="#0f91a5",
        info_hover="#18a8bd",
        info_pressed="#0a6170",
        info_text="#ffffff",
    ),
    tables=TableTheme(
        header_background="#1d2938",
        header_text="#eef4fb",
        grid_line="#324155",
        alternate_row="#141c27",
        hover_row="#1d2a3a",
        match_background="#16422b",
        match_text="#dffbea",
    ),
    tray=TrayTheme(
        surface="rgba(32, 32, 32, 246)",
        control="#2d2d2d",
        row_surface="#282828",
        row_surface_hover="#303030",
        primary_display_surface="#0b2f55",
        primary_display_surface_hover="#103f72",
        primary_display_border="#2b6fa3",
        primary_display_text="#f8fbff",
        control_hover="#383838",
        control_pressed="#444444",
        border="#4a4a4a",
        subtle_border="#3a3a3a",
        text="#f3f3f3",
        muted="#cfcfcf",
        accent="#60cdff",
        accent_hover="#8bddff",
        accent_pressed="#0098d4",
        accent_text="#003547",
        success="#16a34a",
        success_hover="#22c55e",
        success_pressed="#15803d",
        success_text="#ffffff",
        warning="#f59e0b",
        warning_hover="#fbbf24",
        warning_pressed="#d97706",
        warning_text="#241400",
        close_hover="#c42b1c",
        close_pressed="#a4261d",
        close_text="#ffffff",
        indicator_connected="#22c55e",
        indicator_disconnected="#f87171",
        indicator_disabled="#94a3b8",
        ping_idle="#0f172a",
        ping_idle_text="#ffffff",
        faceplate_enabled_bg="#60cdff",
        faceplate_enabled_border="#60cdff",
        faceplate_enabled_text="#003547",
        faceplate_disabled_bg="#0098d4",
        faceplate_disabled_border="#0098d4",
        faceplate_disabled_text="#ffffff",
        faceplate_primary_bg="#bce4ff",
        faceplate_primary_border="#60cdff",
        faceplate_primary_text="#0a1a33",
        faceplate_unavailable_bg="#444444",
        faceplate_unavailable_border="transparent",
        faceplate_unavailable_text="#cfcfcf",
    ),
    metrics=_DEFAULT_METRICS,
)

OCEAN_THEME = AppTheme(
    name="ocean",
    window_background="#eef8fb",
    panel_background="#ffffff",
    panel_border="#b7d8e3",
    control_background="#fbfeff",
    control_border="#9dc8d6",
    control_focus="#0e7490",
    text="#102a33",
    muted_text="#516b76",
    selection_background="#cffafe",
    selection_text="#083344",
    buttons=ButtonTheme(
        default=ButtonRole("#e0f2fe", "#bae6fd", "#7dd3fc", "#0f3443", "#9bd3e8"),
        primary=ButtonRole("#0e7490", "#0c647c", "#0a5368", "#ffffff", "#0b6680"),
        success=ButtonRole("#0f8f68", "#0b7556", "#095f47", "#ffffff", "#0b7556"),
        danger=ButtonRole("#be3b56", "#a33149", "#84283b", "#ffffff", "#a33149"),
        info=ButtonRole("#0284c7", "#0369a1", "#075985", "#ffffff", "#0369a1"),
        accent=ButtonRole("#0d9488", "#0f766e", "#115e59", "#ffffff", "#0f766e"),
        disabled_background="#dbe8ed",
        disabled_text="#7e919a",
        disabled_border="#c6d7de",
    ),
    scene=SceneTheme(
        shelf_fill="#dff7fb",
        shelf_border="#7fb6c6",
        shelf_title="#18596b",
        audio_fill="#123440",
        audio_border="#22d3ee",
        audio_text="#f5fdff",
        object_fill="#e8f5f7",
        object_border="#8fb4bd",
        object_text="#17313a",
        monitor_primary_fill="#c9f0f7",
        monitor_primary_border="#0e7490",
        monitor_fill="#f3fbfd",
        monitor_border="#5f7f8c",
        monitor_text="#102a33",
        monitor_number_primary="#0e7490",
        monitor_number="#5f7f8c",
        monitor_number_alpha=50,
    ),
    palette=PaletteTheme(
        accent="#0e7490",
        accent_hover="#0c647c",
        accent_pressed="#0a5368",
        accent_text="#ffffff",
        success="#0f8f68",
        success_hover="#0b7556",
        success_pressed="#095f47",
        success_text="#ffffff",
        warning="#b7791f",
        warning_hover="#94620e",
        warning_pressed="#724a0a",
        warning_text="#ffffff",
        danger="#be3b56",
        danger_hover="#a33149",
        danger_pressed="#84283b",
        danger_text="#ffffff",
        info="#0284c7",
        info_hover="#0369a1",
        info_pressed="#075985",
        info_text="#ffffff",
    ),
    tables=TableTheme(
        header_background="#e0f2fe",
        header_text="#0f3443",
        grid_line="#b7d8e3",
        alternate_row="#f4fbfd",
        hover_row="#e6f7fb",
        match_background="#d1fae5",
        match_text="#123b2a",
    ),
    tray=TrayTheme(
        surface="rgba(241, 251, 253, 246)",
        control="#ffffff",
        row_surface="#ffffff",
        row_surface_hover="#edf9fc",
        primary_display_surface="#0f3f4e",
        primary_display_surface_hover="#13566a",
        primary_display_border="#0e7490",
        primary_display_text="#f5fdff",
        control_hover="#e8f7fb",
        control_pressed="#d7edf4",
        border="#a7cbd8",
        subtle_border="#d1e7ee",
        text="#102a33",
        muted="#536f79",
        accent="#0e7490",
        accent_hover="#0c647c",
        accent_pressed="#0a5368",
        accent_text="#ffffff",
        success="#0f8f68",
        success_hover="#0b7556",
        success_pressed="#095f47",
        success_text="#ffffff",
        warning="#b7791f",
        warning_hover="#94620e",
        warning_pressed="#724a0a",
        warning_text="#ffffff",
        close_hover="#be3b56",
        close_pressed="#84283b",
        close_text="#ffffff",
        indicator_connected="#0f8f68",
        indicator_disconnected="#be3b56",
        indicator_disabled="#7a939b",
        ping_idle="#0f3443",
        ping_idle_text="#ffffff",
        faceplate_enabled_bg="#0e7490",
        faceplate_enabled_border="#0e7490",
        faceplate_enabled_text="#ffffff",
        faceplate_disabled_bg="#0a5368",
        faceplate_disabled_border="#0a5368",
        faceplate_disabled_text="#ffffff",
        faceplate_primary_bg="#cffafe",
        faceplate_primary_border="#0e7490",
        faceplate_primary_text="#0f3443",
        faceplate_unavailable_bg="#d7edf4",
        faceplate_unavailable_border="transparent",
        faceplate_unavailable_text="#536f79",
    ),
    metrics=_DEFAULT_METRICS,
)

GRAPHITE_THEME = AppTheme(
    name="graphite",
    window_background="#f4f4f5",
    panel_background="#ffffff",
    panel_border="#c8c8cf",
    control_background="#ffffff",
    control_border="#b8bac2",
    control_focus="#52525b",
    text="#18181b",
    muted_text="#5f6067",
    selection_background="#e4e4e7",
    selection_text="#18181b",
    buttons=ButtonTheme(
        default=ButtonRole("#eeeeef", "#e4e4e7", "#d4d4d8", "#27272a", "#c8c8cf"),
        primary=ButtonRole("#3f3f46", "#27272a", "#18181b", "#ffffff", "#27272a"),
        success=ButtonRole("#15803d", "#166534", "#14532d", "#ffffff", "#166534"),
        danger=ButtonRole("#b91c1c", "#991b1b", "#7f1d1d", "#ffffff", "#991b1b"),
        info=ButtonRole("#0369a1", "#075985", "#0c4a6e", "#ffffff", "#075985"),
        accent=ButtonRole("#57534e", "#44403c", "#292524", "#ffffff", "#44403c"),
        disabled_background="#e4e4e7",
        disabled_text="#8a8c94",
        disabled_border="#d4d4d8",
    ),
    scene=SceneTheme(
        shelf_fill="#eeeeef",
        shelf_border="#a1a1aa",
        shelf_title="#3f3f46",
        audio_fill="#27272a",
        audio_border="#a1a1aa",
        audio_text="#fafafa",
        object_fill="#f4f4f5",
        object_border="#a1a1aa",
        object_text="#27272a",
        monitor_primary_fill="#e4e4e7",
        monitor_primary_border="#52525b",
        monitor_fill="#fafafa",
        monitor_border="#71717a",
        monitor_text="#18181b",
        monitor_number_primary="#3f3f46",
        monitor_number="#71717a",
        monitor_number_alpha=50,
    ),
    palette=PaletteTheme(
        accent="#3f3f46",
        accent_hover="#27272a",
        accent_pressed="#18181b",
        accent_text="#ffffff",
        success="#15803d",
        success_hover="#166534",
        success_pressed="#14532d",
        success_text="#ffffff",
        warning="#a16207",
        warning_hover="#854d0e",
        warning_pressed="#713f12",
        warning_text="#ffffff",
        danger="#b91c1c",
        danger_hover="#991b1b",
        danger_pressed="#7f1d1d",
        danger_text="#ffffff",
        info="#0369a1",
        info_hover="#075985",
        info_pressed="#0c4a6e",
        info_text="#ffffff",
    ),
    tables=TableTheme(
        header_background="#eeeeef",
        header_text="#27272a",
        grid_line="#d4d4d8",
        alternate_row="#fafafa",
        hover_row="#eeeeef",
        match_background="#dcfce7",
        match_text="#14532d",
    ),
    tray=TrayTheme(
        surface="rgba(248, 248, 249, 246)",
        control="#ffffff",
        row_surface="#ffffff",
        row_surface_hover="#f4f4f5",
        primary_display_surface="#27272a",
        primary_display_surface_hover="#3f3f46",
        primary_display_border="#71717a",
        primary_display_text="#ffffff",
        control_hover="#eeeeef",
        control_pressed="#e4e4e7",
        border="#c8c8cf",
        subtle_border="#e4e4e7",
        text="#18181b",
        muted="#5f6067",
        accent="#3f3f46",
        accent_hover="#27272a",
        accent_pressed="#18181b",
        accent_text="#ffffff",
        success="#15803d",
        success_hover="#166534",
        success_pressed="#14532d",
        success_text="#ffffff",
        warning="#a16207",
        warning_hover="#854d0e",
        warning_pressed="#713f12",
        warning_text="#ffffff",
        close_hover="#b91c1c",
        close_pressed="#7f1d1d",
        close_text="#ffffff",
        indicator_connected="#15803d",
        indicator_disconnected="#b91c1c",
        indicator_disabled="#71717a",
        ping_idle="#18181b",
        ping_idle_text="#ffffff",
        faceplate_enabled_bg="#3f3f46",
        faceplate_enabled_border="#3f3f46",
        faceplate_enabled_text="#ffffff",
        faceplate_disabled_bg="#18181b",
        faceplate_disabled_border="#18181b",
        faceplate_disabled_text="#ffffff",
        faceplate_primary_bg="#e4e4e7",
        faceplate_primary_border="#3f3f46",
        faceplate_primary_text="#18181b",
        faceplate_unavailable_bg="#e4e4e7",
        faceplate_unavailable_border="transparent",
        faceplate_unavailable_text="#5f6067",
    ),
    metrics=_DEFAULT_METRICS,
)

HIGH_CONTRAST_THEME = AppTheme(
    name="high_contrast",
    window_background="#000000",
    panel_background="#000000",
    panel_border="#ffffff",
    control_background="#000000",
    control_border="#ffffff",
    control_focus="#ffff00",
    text="#ffffff",
    muted_text="#d6d6d6",
    selection_background="#ffff00",
    selection_text="#000000",
    buttons=ButtonTheme(
        default=ButtonRole("#000000", "#1a1a1a", "#333333", "#ffffff", "#ffffff"),
        primary=ButtonRole("#ffff00", "#fff176", "#ffd600", "#000000", "#ffff00"),
        success=ButtonRole("#00ff66", "#43ff8f", "#00cc52", "#000000", "#00ff66"),
        danger=ButtonRole("#ff4d4d", "#ff6b6b", "#cc0000", "#000000", "#ff4d4d"),
        info=ButtonRole("#00e5ff", "#5ef4ff", "#00b8cc", "#000000", "#00e5ff"),
        accent=ButtonRole("#ff8cff", "#ffb3ff", "#d95fd9", "#000000", "#ff8cff"),
        disabled_background="#262626",
        disabled_text="#8c8c8c",
        disabled_border="#777777",
    ),
    scene=SceneTheme(
        shelf_fill="#000000",
        shelf_border="#ffffff",
        shelf_title="#ffff00",
        audio_fill="#000000",
        audio_border="#00e5ff",
        audio_text="#ffffff",
        object_fill="#000000",
        object_border="#ffffff",
        object_text="#ffffff",
        monitor_primary_fill="#000000",
        monitor_primary_border="#ffff00",
        monitor_fill="#000000",
        monitor_border="#ffffff",
        monitor_text="#ffffff",
        monitor_number_primary="#ffff00",
        monitor_number="#ffffff",
        monitor_number_alpha=90,
    ),
    palette=PaletteTheme(
        accent="#ffff00",
        accent_hover="#fff176",
        accent_pressed="#ffd600",
        accent_text="#000000",
        success="#00ff66",
        success_hover="#43ff8f",
        success_pressed="#00cc52",
        success_text="#000000",
        warning="#ffcc00",
        warning_hover="#ffdd4d",
        warning_pressed="#d6aa00",
        warning_text="#000000",
        danger="#ff4d4d",
        danger_hover="#ff6b6b",
        danger_pressed="#cc0000",
        danger_text="#000000",
        info="#00e5ff",
        info_hover="#5ef4ff",
        info_pressed="#00b8cc",
        info_text="#000000",
    ),
    tables=TableTheme(
        header_background="#000000",
        header_text="#ffffff",
        grid_line="#ffffff",
        alternate_row="#111111",
        hover_row="#1f1f1f",
        match_background="#ffff00",
        match_text="#000000",
    ),
    tray=TrayTheme(
        surface="rgba(0, 0, 0, 252)",
        control="#000000",
        row_surface="#000000",
        row_surface_hover="#1a1a1a",
        primary_display_surface="#000000",
        primary_display_surface_hover="#1a1a1a",
        primary_display_border="#ffff00",
        primary_display_text="#ffffff",
        control_hover="#1a1a1a",
        control_pressed="#333333",
        border="#ffffff",
        subtle_border="#777777",
        text="#ffffff",
        muted="#d6d6d6",
        accent="#ffff00",
        accent_hover="#fff176",
        accent_pressed="#ffd600",
        accent_text="#000000",
        success="#00ff66",
        success_hover="#43ff8f",
        success_pressed="#00cc52",
        success_text="#000000",
        warning="#ffcc00",
        warning_hover="#ffdd4d",
        warning_pressed="#d6aa00",
        warning_text="#000000",
        close_hover="#ff4d4d",
        close_pressed="#cc0000",
        close_text="#000000",
        indicator_connected="#00ff66",
        indicator_disconnected="#ff4d4d",
        indicator_disabled="#d6d6d6",
        ping_idle="#000000",
        ping_idle_text="#ffffff",
        faceplate_enabled_bg="#ffff00",
        faceplate_enabled_border="#ffff00",
        faceplate_enabled_text="#000000",
        faceplate_disabled_bg="#ffd600",
        faceplate_disabled_border="#ffd600",
        faceplate_disabled_text="#000000",
        faceplate_primary_bg="#ffffff",
        faceplate_primary_border="#ffff00",
        faceplate_primary_text="#000000",
        faceplate_unavailable_bg="#333333",
        faceplate_unavailable_border="transparent",
        faceplate_unavailable_text="#d6d6d6",
    ),
    metrics=_DEFAULT_METRICS,
)

_ACCENT_SPECS = {
    "red": ("#dc2626", "#b91c1c", "#991b1b", "#f87171"),
    "blue": ("#2563eb", "#1d4ed8", "#1e40af", "#60a5fa"),
    "green": ("#16a34a", "#15803d", "#166534", "#4ade80"),
    "purple": ("#7c3aed", "#6d28d9", "#5b21b6", "#a78bfa"),
    "orange": ("#ea580c", "#c2410c", "#9a3412", "#fb923c"),
    "pink": ("#db2777", "#be185d", "#9d174d", "#f472b6"),
}


def _make_accent_theme(
    color: str,
    mode: str,
    accent: str,
    hover: str,
    pressed: str,
    light: str,
) -> AppTheme:
    dark = mode == "dark"
    name = f"{color}_{mode}"
    if dark:
        window_background = "#10151d"
        panel_background = "#171f2b"
        panel_border = "#324155"
        control_background = "#111923"
        control_border = "#40536b"
        text = "#eef4fb"
        muted = "#a8b5c6"
        selection_background = "#263a52"
        selection_text = "#ffffff"
        default_button = ButtonRole("#223047", "#2b3b55", "#182235", text, "#40536b")
        table = TableTheme(
            header_background="#1d2938",
            header_text=text,
            grid_line=panel_border,
            alternate_row="#141c27",
            hover_row="#1d2a3a",
            match_background="#16422b",
            match_text="#dffbea",
        )
        scene = SceneTheme(
            shelf_fill="#142436",
            shelf_border="#3f6b8f",
            shelf_title="#b7d7f0",
            audio_fill="#0b1722",
            audio_border=accent,
            audio_text="#f3f9ff",
            object_fill="#1c2836",
            object_border="#617388",
            object_text="#e6edf5",
            monitor_primary_fill="#183657",
            monitor_primary_border=accent,
            monitor_fill="#202b38",
            monitor_border="#7b8ca1",
            monitor_text=text,
            monitor_number_primary=accent,
            monitor_number="#9fb0c3",
            monitor_number_alpha=70,
        )
        tray = TrayTheme(
            surface="rgba(32, 32, 32, 246)",
            control="#2d2d2d",
            row_surface="#282828",
            row_surface_hover="#303030",
            primary_display_surface="#141f30",
            primary_display_surface_hover="#1c2d45",
            primary_display_border=accent,
            primary_display_text="#f8fbff",
            control_hover="#383838",
            control_pressed="#444444",
            border="#4a4a4a",
            subtle_border="#3a3a3a",
            text="#f3f3f3",
            muted="#cfcfcf",
            accent=accent,
            accent_hover=hover,
            accent_pressed=pressed,
            accent_text="#ffffff",
            success="#16a34a",
            success_hover="#22c55e",
            success_pressed="#15803d",
            success_text="#ffffff",
            warning="#f59e0b",
            warning_hover="#fbbf24",
            warning_pressed="#d97706",
            warning_text="#241400",
            close_hover="#c42b1c",
            close_pressed="#a4261d",
            close_text="#ffffff",
            indicator_connected="#22c55e",
            indicator_disconnected="#f87171",
            indicator_disabled="#94a3b8",
            ping_idle="#0f172a",
            ping_idle_text="#ffffff",
            faceplate_enabled_bg=accent,
            faceplate_enabled_border=accent,
            faceplate_enabled_text="#ffffff",
            faceplate_disabled_bg=pressed,
            faceplate_disabled_border=pressed,
            faceplate_disabled_text="#ffffff",
            faceplate_primary_bg=light,
            faceplate_primary_border=accent,
            faceplate_primary_text="#1a1a1a",
            faceplate_unavailable_bg="#444444",
            faceplate_unavailable_border="transparent",
            faceplate_unavailable_text="#cfcfcf",
        )
    else:
        window_background = "#f6f8fb"
        panel_background = "#ffffff"
        panel_border = "#d7deea"
        control_background = "#ffffff"
        control_border = "#c8d2e3"
        text = "#162033"
        muted = "#5d6b82"
        selection_background = "#e8eef9"
        selection_text = "#0f2344"
        default_button = ButtonRole("#eef2f8", "#e2e8f0", "#cbd5e1", "#1e3154", "#c8d2e3")
        table = TableTheme(
            header_background="#eef3fb",
            header_text="#24324f",
            grid_line=panel_border,
            alternate_row="#f8fbff",
            hover_row="#edf5ff",
            match_background="#dcfce7",
            match_text="#12301c",
        )
        scene = SceneTheme(
            shelf_fill="#f0f7ff",
            shelf_border="#93b4dd",
            shelf_title="#31537c",
            audio_fill="#24324f",
            audio_border=accent,
            audio_text="#f8fbff",
            object_fill="#eef3fb",
            object_border="#9aa9bd",
            object_text="#24324f",
            monitor_primary_fill="#e8eef9",
            monitor_primary_border=accent,
            monitor_fill="#f5f9ff",
            monitor_border="#64748b",
            monitor_text=text,
            monitor_number_primary=accent,
            monitor_number="#64748b",
            monitor_number_alpha=46,
        )
        tray = TrayTheme(
            surface="rgba(249, 249, 249, 245)",
            control="#ffffff",
            row_surface="#ffffff",
            row_surface_hover="#f8fafc",
            primary_display_surface="#0b2f55",
            primary_display_surface_hover="#103f72",
            primary_display_border=accent,
            primary_display_text="#f8fbff",
            control_hover="#f3f3f3",
            control_pressed="#e9e9e9",
            border="#d1d1d1",
            subtle_border="#e5e5e5",
            text="#1a1a1a",
            muted="#616161",
            accent=accent,
            accent_hover=hover,
            accent_pressed=pressed,
            accent_text="#ffffff",
            success="#107c10",
            success_hover="#0e6f0e",
            success_pressed="#0b5a0b",
            success_text="#ffffff",
            warning="#b45309",
            warning_hover="#92400e",
            warning_pressed="#78350f",
            warning_text="#ffffff",
            close_hover="#c42b1c",
            close_pressed="#a4261d",
            close_text="#ffffff",
            indicator_connected="#107c10",
            indicator_disconnected="#c42b1c",
            indicator_disabled="#7f8c8d",
            ping_idle="#000000",
            ping_idle_text="#ffffff",
            faceplate_enabled_bg=accent,
            faceplate_enabled_border=accent,
            faceplate_enabled_text="#ffffff",
            faceplate_disabled_bg=pressed,
            faceplate_disabled_border=pressed,
            faceplate_disabled_text="#ffffff",
            faceplate_primary_bg=light,
            faceplate_primary_border=accent,
            faceplate_primary_text="#1a1a1a",
            faceplate_unavailable_bg="#e9e9e9",
            faceplate_unavailable_border="transparent",
            faceplate_unavailable_text="#616161",
        )
    return AppTheme(
        name=name,
        window_background=window_background,
        panel_background=panel_background,
        panel_border=panel_border,
        control_background=control_background,
        control_border=control_border,
        control_focus=accent,
        text=text,
        muted_text=muted,
        selection_background=selection_background,
        selection_text=selection_text,
        buttons=ButtonTheme(
            default=default_button,
            primary=ButtonRole(accent, hover, pressed, "#ffffff", hover),
            success=ButtonRole("#16a34a", "#15803d", "#166534", "#ffffff", "#15803d"),
            danger=ButtonRole("#dc2626", "#b91c1c", "#991b1b", "#ffffff", "#b91c1c"),
            info=ButtonRole("#0891b2", "#0e7490", "#155e75", "#ffffff", "#0e7490"),
            accent=ButtonRole(accent, hover, pressed, "#ffffff", hover),
            disabled_background="#1b2431" if dark else "#e4e9f2",
            disabled_text="#66758a" if dark else "#8a96aa",
            disabled_border="#2d3a4d" if dark else "#d0d8e5",
        ),
        scene=scene,
        palette=PaletteTheme(
            accent=accent,
            accent_hover=hover,
            accent_pressed=pressed,
            accent_text="#ffffff",
            success="#16a34a",
            success_hover="#22c55e" if dark else "#15803d",
            success_pressed="#15803d" if dark else "#166534",
            success_text="#ffffff",
            warning="#f59e0b" if dark else "#b45309",
            warning_hover="#fbbf24" if dark else "#92400e",
            warning_pressed="#d97706" if dark else "#78350f",
            warning_text="#241400" if dark else "#ffffff",
            danger="#dc2626",
            danger_hover="#b91c1c",
            danger_pressed="#991b1b",
            danger_text="#ffffff",
            info="#0891b2",
            info_hover="#0e7490",
            info_pressed="#155e75",
            info_text="#ffffff",
        ),
        tables=table,
        tray=tray,
        metrics=_DEFAULT_METRICS,
    )


ACCENT_THEMES = tuple(
    _make_accent_theme(color, mode, *spec)
    for color, spec in _ACCENT_SPECS.items()
    for mode in ("light", "dark")
)

THEMES = {
    DEFAULT_THEME.name: DEFAULT_THEME,
    DARK_THEME.name: DARK_THEME,
    OCEAN_THEME.name: OCEAN_THEME,
    GRAPHITE_THEME.name: GRAPHITE_THEME,
    HIGH_CONTRAST_THEME.name: HIGH_CONTRAST_THEME,
    **{theme.name: theme for theme in ACCENT_THEMES},
}
